#!/usr/bin/env bash

set -Eeu -o pipefail

user_config() {
    INSTALL_USER=""

    # NOTE! Change the values below to your own
    # Or comment out to disable installation
    # SSH_REMOTE_ACCESS_PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOF7pdrlAiVSJaaynnpEJJ3/1jAmtrPUSNP7/pHIg7bF phunt@agnate"
    # ZEROTIER_NETWORK="8286ac0e47fafe85"

    # Change the value below to change the hostname
    CHANGE_HOSTNAME_TO=""

    # Set a static IP address for an Interface
    # STATIC_IFACE="eno1"
    # STATIC_ADDRESS="192.168.250.302/24"
}

main() {
    user_config

    if [[ -z $INSTALL_USER ]]; then
        die "must customize user_config before running; hint: ${EDITOR:-nano} $0"
    fi

    HOME=/home/$INSTALL_USER

    require_root
    fail_if_no_user

    check_ubuntu_version
    change_hostname
    configure_apt
    setup_zsh
    setup_ssh
    setup_screen
    setup_git
    setup_vim
    setup_nvim
    setup_static_ip_address
    install_development_packages
    install_ripgrep
    install_fd
    install_fasd
    configure_system
    configure_network eno1
    disable_automatic_updates
    disable_unwanted_services
    disable_login_messages
    cleanup_user_home
    configure_gnome_settings
    disable_suspend_on_lid_closed
    configure_x11vnc_remote_access
    disable_graphical_grub
    cloudflare_dns
    install_wireless_build_packages
    install_zerotier
    remove_applications

    info "prestobuntu setup complete!"
}

mute() { "$@" &>/dev/null; }

require_root() {
    if (( UID != 0 )); then
        die "must run as root; tip: sudo ./setup"
    fi
}

apt_update() {
    if [[ ! -v HAVE_APT_UPDATE ]]; then
        apt-get update
        HAVE_APT_UPDATE=1
    fi
}

fail_if_no_user() {
    if ! mute id -u $INSTALL_USER; then
        die "cowardly refusing to run since $INSTALL_USER account does not exist"
    fi
}

install_package() {
    for pkg in "$@"; do
        if ! dpkg -s "$pkg" | grep -q "Status: install ok installed"; then
            apt_update
            info "installing $pkg"
            apt-get install -y "$pkg"
        fi
    done
}

remove_package() {
    if ! dpkg -s "$1" 2>&1 | grep -q "is not installed"; then
        info "uninstalling $1"
        apt-get purge -y "$1"
    fi
}

check_ubuntu_version() {
    UBUNTU_VERSION=$(grep RELEASE /etc/lsb-release | grep -Eo '[0-9.]+')
    UBUNTU_VERSION=${UBUNTU_VERSION%%.*}  # keep major version only, e.g. 18

    if (( UBUNTU_VERSION < 18 )); then
        die "prestobuntu only supported on Ubuntu 18.04 or higher"
    fi
}

change_hostname() {
    if [[ -v CHANGE_HOSTNAME_TO && $CHANGE_HOSTNAME_TO ]]; then
        sudo hostnamectl set-hostname "$CHANGE_HOSTNAME_TO"
    fi
}

configure_apt() {
    : kill running apt inhibitors
    unwanted='apt|aptd|unattended-upgrade'
    while pgrep -f "$unwanted"; do
        pkill -f "$unwanted" ||:
        sleep 0.5
    done
}

configure_system() {
    if ! grep -q NOPASSWD /etc/sudoers; then
        : Allow sudo without password
        sed -E -i.bak 's|^(%sudo.+ALL:ALL\)) (ALL)|\1 NOPASSWD: \2|' /etc/sudoers
    fi

    if ! grep -q ctrl:nocaps /etc/default/keyboard; then
        : Remap CapsLock key as Ctrl
        sed -E -i.bak 's|^(XKBOPTIONS=")(")|\1ctrl:nocaps\2|' /etc/default/keyboard
    fi

    : make journald persistent
    mkdir -p /var/log/journal

    : configure motd to remove update messages
    (cd /etc/update-motd.d
     chmod -x 10-help-text 90-updates-available 91-release-upgrade)
}

configure_network() {
    if (( UBUNTU_VERSION >= 20 )); then
        # Ubuntu 20.04 and higher use netplan
        return
    fi

    if grep -q prestobuntu /etc/network/interfaces; then
        return
    fi

    cat >>/etc/network/interfaces <<EOF

# added by prestobuntu
auto $1
iface $1 inet static
address 192.168.250.40/24

auto $1:1
iface $1:1 inet dhcp
EOF
}

as_user() {
    sudo -u $INSTALL_USER "$@"
}

setup_ssh() {
    install_package openssh-server

    if [[ -v SSH_REMOTE_ACCESS_PUBKEY ]]; then
        as_user mkdir -p $HOME/.ssh --mode 700
        as_user touch $HOME/.ssh/authorized_keys
        _require_line "$SSH_REMOTE_ACCESS_PUBKEY" $HOME/.ssh/authorized_keys
        chmod 600 $HOME/.ssh/authorized_keys
    fi

    # make sure this system has ssh keys
    if ! test -f ~/.ssh/id_rsa; then
        ssh-keygen -N "" -f "$_"
    fi
}

setup_git() {
    install_package git
    get_prestobuntu_file gitconfig $HOME/.gitconfig
}

get_internet_file() {
    as_user wget "$1" --output-document "$2"
}

get_prestobuntu_file() {
    base="https://raw.githubusercontent.com/presto8/prestobuntu/master"
    get_internet_file "$base/$1" "$2"
}

setup_zsh() {
    install_package zsh
    chsh -s /usr/bin/zsh $INSTALL_USER

    get_prestobuntu_file zshrc $HOME/.zshrc
    get_internet_file "https://raw.githubusercontent.com/nojhan/liquidprompt/master/liquidprompt" $HOME/.liquidprompt
    # change some colors to look better with dark background
    _sed "    LP_COLOR_SSH=.*" "    LP_COLOR_SSH=\$BOLD_WHITE" $HOME/.liquidprompt
}

setup_screen() {
    install_package screen

    as_user tee $HOME/.screenrc <<'EOF'
startup_message off
hardstatus alwayslastline
hardstatus string '%{= Kd} %{= Kd}%-w%{= Kr}[%{= KW}%n %t%{= Kr}]%{= Kd}%+w %-= %{KG} %H%{KW}|%{KY}%101`%{KW}|%D %M %d%{= Kc} %C%A%{-}'

# https://gist.github.com/martijnvermaat/8070533#gistcomment-1317075
setenv SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock
EOF
}

install_development_packages() {
    install_package exuberant-ctags
    install_package flake8
    install_package python3-pip
    install_ccache
    hash -r
}

install_ccache() {
    install_package ccache
    for i in gcc g++ cc c++; do
        ln -s "$(which ccache)" "/usr/local/bin/$i"
    done
}

install_ripgrep() {
    # ripgrep not available via apt install so have to install this way
    get_internet_file "https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb" /tmp/ripgrep.deb
    dpkg -i "$_"
}

install_fd() {
    if (( UBUNTU_VERSION >= 19 )); then
        install_package fd-find
    else
        get_internet_file https://github.com/sharkdp/fd/releases/download/v8.1.1/fd_8.1.1_amd64.deb /tmp/fd.deb
        dpkg -i "$_"
    fi
}

install_fasd() {
    # provides z for quickjump cd, v for quickedit vim, etc.
    install_package fasd
}

setup_vim() {
    install_package vim-gtk3

    local autoload=$HOME/.vim/autoload
    as_user mkdir -p $autoload

    get_internet_file "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" $autoload/plug.vim
    get_prestobuntu_file vimrc $HOME/.vim/vimrc

    as_user vim +'PlugInstall --sync' +qa
}

setup_nvim() {
    install_package neovim
    as_user mkdir -p $HOME/.config/nvim
}

setup_static_ip_address() {
    if [[ -v STATIC_IFACE && $STATIC_IFACE ]]; then
        connection_name=$(nmcli -g general.connection device show "$STATIC_IFACE")
        nmcli connection modify "$connection_name" ipv4.addresses "$STATIC_ADDRESS"
        nmcli connection modify "$connection_name" ipv4.method manual
    fi
}

disable_unwanted_services() {
    systemctl disable --now cups cups-browsed
    systemctl disable --now whoopsie
    systemctl disable --now avahi-daemon ||:

    # note: can't uninstall evolution since it will break Ubuntu; prevent the processes from starting
    find /usr/libexec -type f -name 'evolution-*' -exec chmod -x "{}" \;
}

disable_login_messages() {
    touch $HOME/.hushlogin
}

disable_graphical_grub() {
    sed -E -i.bak -e 's|^(GRUB_CMDLINE_LINUX_DEFAULT=")quiet splash(")|\1text\2|' \
                  -e 's|^(GRUB_TIMEOUT_STYLE=).*|\1menu|' \
                  -e 's|^(GRUB_TIMEOUT=).*|\110|' \
                  /etc/default/grub
    update-grub
}

_sed() {
    local from=$1 to=$2 file=$3
    sed -E -i.bak "s|$from|$to|g" "$file"
}

_require_line() {
    # adds line if not present
    local line="$1" file="$2"
    if ! grep -qs --line-regexp --fixed-strings "$line" "$file"; then
        echo "$line" >>"$file"
    fi
}

cloudflare_dns() {
    : configure CloudFlare to take priority over DHCP provided DNS
    local resolv
    resolv=$(head -1 /etc/resolv.conf)
    if [[ $resolv =~ resolvconf ]]; then
        _require_line "nameserver 1.1.1.1" /etc/resolvconf/resolv.conf.d/head
    elif [[ $resolv =~ systemd-resolved ]]; then
        _sed "^#DNS=" "DNS=1.1.1.1" /etc/systemd/resolved.conf
        systemctl restart systemd-resolved
    fi
}

install_wireless_build_packages() {
    : install packages needed to compile wpa_supplicant, hostapd, and iwlwifi
    for i in build-essential libnl-3-dev libnl-genl-3-dev bison flex libssl-dev libreadline-dev libncurses-dev; do
        install_package "$i"
    done
}

install_zerotier() {
    get_internet_file https://install.zerotier.com /tmp/zerotier.install
    sudo bash "$_"
    if [[ -v ZEROTIER_NETWORK ]]; then
        sudo zerotier-cli join "$ZEROTIER_NETWORK"
    fi
}

remove_applications() {
    remove_package thunderbird
    remove_package rhythmbox
}

disable_automatic_updates() {
    systemctl disable --now apt-daily.timer
    systemctl disable --now unattended-upgrades
    systemctl disable --now packagekit
    systemctl disable --now apt-daily-upgrade.timer

    sed -E -i.bak 's|"1"|"0"|' /etc/apt/apt.conf.d/10periodic
    sed -E -i.bak 's|"1"|"0"|' /etc/apt/apt.conf.d/20auto-upgrades
    sed -E -i.bak 's|^([^#])|#\1|g' /etc/apt/apt.conf.d/99update-notifier

    pkill -9 update-notifier ||:
    pkill -9 update-manager ||:

    chmod 000 /etc/xdg/autostart/update-notifier.desktop
}

cleanup_user_home() {
    find /home/$INSTALL_USER -maxdepth 1 -type d -empty '!' -name Desktop -delete ||:
    find /home/$INSTALL_USER -name examples.desktop -delete ||:
}

configure_gnome_settings() {
    gsettings="sudo -u $INSTALL_USER -H dbus-launch gsettings"
    $gsettings set org.gnome.desktop.wm.preferences focus-mode 'sloppy'
    $gsettings set org.gnome.desktop.screensaver lock-enabled false
    $gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false
    $gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll true
    $gsettings set org.gnome.settings-daemon.plugins.power lid-close-ac-action 'nothing'

    if (( UBUNTU_VERSION >= 20 )); then
        : disable ubuntu/gnome welcome wizard
        as_user touch $HOME/.config/gnome-initial-setup-done
        pkill -9 -f gnome-initial-setup ||:
    fi
}

disable_suspend_on_lid_closed() {
    _require_line "HandleLidSwitch=ignore" /etc/systemd/logind.conf
    _require_line "HandleLidSwitchExternalPower=ignore" /etc/systemd/logind.conf
    # TODO: below command causes session to end and user logout
    # systemctl restart systemd-logind
}

configure_x11vnc_remote_access() {
    install_package x11vnc
    cat >/etc/systemd/system/x11vnc.service <<EOF
[Unit]
Description=x11vnc Service
After=multi-user.target

[Service]
Type=Simple
ExecStart=/usr/bin/x11vnc -forever -display :0 -auth /run/user/1000/gdm/Xauthority -ncache 10
Restart=always

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable --now x11vnc
}

_info_helper() {
    local color=$1 prefix=$2 ; shift 2
    echo -e "\033[${color}m${prefix}$*\e[0m"
}
info() { _info_helper 36 ":: " "$@" ; }
die() { _info_helper 31 "!! " "$@" ; exit 1; }

main "$@"
